name: Trigger auto deployment for rustwebapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'dockerfile/**'
    - '.github/workflows/rustwebapp-AutoDeployTrigger-e66adab9-7768-422a-9861-35cf7704baa0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RUSTWEBAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RUSTWEBAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RUSTWEBAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/dockerfile 
          registryUrl: docker.io
          registryUsername: ${{ secrets.RUSTWEBAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RUSTWEBAPP_REGISTRY_PASSWORD }}
          containerAppName: rustwebapp
          resourceGroup: rg-rusttut
          imageToBuild: desmondzhu/rustwebapp:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


